import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { Check, Circle, Clock3, Edit3, Play, Plus, RefreshCw, Target, X } from 'lucide-react'
import { listTasks, updateTaskStatus } from './tasksApi'
import { archiveTask, createTask, listTaskOptions, startTask, updateTask } from './taskExecutionApi'
import { emptyTaskForm, type TaskFormValues } from './taskForm'
import type { Task } from './types'

const priorityOrder: Record<string, number> = { urgent: 0, high: 1, medium: 2, low: 3 }
const priorityClass = (p: string) => p === 'urgent' ? 'bg-red-500/10 text-red-300' : p === 'high' ? 'bg-orange-500/10 text-orange-300' : p === 'medium' ? 'bg-yellow-500/10 text-yellow-300' : 'bg-[var(--surface-2)] text-[var(--muted)]'
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : null
const toInputDate = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : ''

export function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([])
  const [options, setOptions] = useState<{ goals: { id: string; title: string }[]; lifeAreas: { id: string; name: string }[] }>({ goals: [], lifeAreas: [] })
  const [loading, setLoading] = useState(true)
  const [busyId, setBusyId] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [filter, setFilter] = useState<'open' | 'completed' | 'all'>('open')
  const [editor, setEditor] = useState<{ open: boolean; task: Task | null }>({ open: false, task: null })

  const load = useCallback(async () => {
    setLoading(true); setError(null)
    try { const [items, taskOptions] = await Promise.all([listTasks(), listTaskOptions()]); setTasks(items); setOptions(taskOptions) }
    catch (e) { setError(e instanceof Error ? e.message : 'Unable to load tasks.') }
    finally { setLoading(false) }
  }, [])
  useEffect(() => { void load() }, [load])
  const visibleTasks = useMemo(() => tasks.filter(t => filter === 'all' || (filter === 'completed' ? t.status === 'completed' : !['completed', 'cancelled', 'skipped'].includes(t.status))).sort((a,b) => (priorityOrder[a.priority] ?? 9) - (priorityOrder[b.priority] ?? 9)), [filter, tasks])
  async function toggle(task: Task) { setBusyId(task.id); setError(null); try { const updated = await updateTaskStatus(task.id, task.status === 'completed' ? 'planned' : 'completed'); setTasks(current => current.map(item => item.id === task.id ? updated : item)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update the task.') } finally { setBusyId(null) } }
  async function begin(task: Task) { setBusyId(task.id); setError(null); try { const updated = await startTask(task.id); setTasks(current => current.map(item => item.id === task.id ? updated : item)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to start the task.') } finally { setBusyId(null) } }
  function openEditor(task?: Task) { setEditor({ open: true, task: task ?? null }) }
  async function save(values: TaskFormValues) { if (!values.title.trim()) return; setError(null); try { const saved = editor.task ? await updateTask(editor.task.id, values) : await createTask(values); setTasks(current => editor.task ? current.map(item => item.id === saved.id ? saved : item) : [saved, ...current]); setEditor({ open: false, task: null }) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save the task.') } }
  async function archive(task: Task) { if (!window.confirm(`Archive “${task.title}”?`)) return; setBusyId(task.id); setError(null); try { await archiveTask(task.id); setTasks(current => current.map(item => item.id === task.id ? { ...item, status: 'cancelled' } : item)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to archive the task.') } finally { setBusyId(null) } }

  return <section className="mx-auto max-w-6xl px-5 py-8 lg:px-10">
    <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-[var(--accent)]">Execution</p><h1 className="text-3xl font-semibold tracking-tight">Tasks</h1><p className="mt-2 text-sm text-[var(--muted)]">Turn goals into concrete actions and close the loop.</p></div><div className="flex gap-2"><button onClick={() => openEditor()} className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>New task</button><button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-2.5 text-sm font-medium hover:bg-[var(--surface-2)] disabled:opacity-50"><RefreshCw size={15} className={loading ? 'animate-spin' : ''}/>Refresh</button></div></header>
    <div className="mb-5 flex flex-wrap gap-2">{(['open','completed','all'] as const).map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-xl px-4 py-2 text-sm font-medium capitalize ${filter === value ? 'bg-[var(--accent)] text-white' : 'border border-[var(--border)] bg-[var(--surface)] text-[var(--muted)]'}`}>{value}</button>)}</div>
    {error && <div className="mb-5 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-sm text-red-200">{error}</div>}
    {loading && !tasks.length ? <div className="space-y-3">{[1,2,3,4].map(i => <div key={i} className="h-20 animate-pulse rounded-2xl bg-[var(--surface)]"/>)}</div> : visibleTasks.length ? <div className="space-y-3">{visibleTasks.map(task => { const completed = task.status === 'completed'; const due = formatDate(task.due_at); return <article key={task.id} className="flex gap-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><button onClick={() => void toggle(task)} disabled={busyId === task.id} aria-label={completed ? `Reopen ${task.title}` : `Complete ${task.title}`} className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-full border ${completed ? 'border-emerald-400/40 bg-emerald-400/10 text-emerald-300' : 'border-[var(--border)] text-[var(--muted)] hover:border-[var(--accent)]'}`}>{completed ? <Check size={16}/> : <Circle size={16}/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className={`font-medium ${completed ? 'text-[var(--muted)] line-through' : ''}`}>{task.title}</h2>{task.description && <p className="mt-1 text-sm text-[var(--muted)]">{task.description}</p>}</div><span className={`rounded-lg px-2 py-1 text-[10px] font-semibold uppercase tracking-wide ${priorityClass(task.priority)}`}>{task.priority}</span></div><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[var(--muted)]">{due && <span className="inline-flex items-center gap-1"><Clock3 size={12}/>{due}</span>}{task.life_area_name && <span>{task.life_area_name}</span>}{task.goal_title && <span className="inline-flex items-center gap-1"><Target size={12}/>{task.goal_title}</span>}{task.estimated_minutes && <span>{task.estimated_minutes} min</span>}<span className="capitalize">{task.status.replace('_',' ')}</span></div></div><div className="flex shrink-0 items-start gap-1">{!completed && <button onClick={() => void begin(task)} disabled={busyId === task.id} title="Start" className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-2)] hover:text-white"><Play size={15}/></button>}<button onClick={() => openEditor(task)} title="Edit" className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-2)] hover:text-white"><Edit3 size={15}/></button>{!completed && <button onClick={() => void archive(task)} disabled={busyId === task.id} title="Archive" className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-2)] hover:text-red-300"><X size={15}/></button>}</div></article> })}</div> : <div className="rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)] p-12 text-center"><Check className="mx-auto text-emerald-300" size={28}/><h2 className="mt-3 font-semibold">No tasks here</h2><p className="mt-1 text-sm text-[var(--muted)]">Create an action from a goal and start executing.</p></div>}
    {editor.open && <TaskEditor task={editor.task} options={options} onClose={() => setEditor({ open:false, task:null })} onSave={save}/>} 
  </section>
}

function TaskEditor({ task, options, onClose, onSave }: { task: Task | null; options: { goals: { id:string; title:string }[]; lifeAreas: { id:string; name:string }[] }; onClose: () => void; onSave: (values: TaskFormValues) => Promise<void> }) {
  const [form, setForm] = useState<TaskFormValues>(() => task ? { title: task.title, description: task.description ?? '', priority: (task.priority as TaskFormValues['priority']) || 'medium', status: task.status === 'in_progress' ? 'in_progress' : task.status === 'inbox' ? 'inbox' : 'planned', due_at: toInputDate(task.due_at), start_at: toInputDate(task.start_at), estimated_minutes: task.estimated_minutes?.toString() ?? '', goal_id: task.goal_id ?? '', life_area_id: task.life_area_id ?? '' } : emptyTaskForm)
  const set = <K extends keyof TaskFormValues>(key: K, value: TaskFormValues[K]) => setForm(current => ({ ...current, [key]: value }))
  const input = 'w-full rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-3 py-2.5 outline-none focus:border-[var(--accent)]'
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="w-full max-w-2xl rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--accent)]">Task</p><h2 className="mt-1 text-xl font-semibold">{task ? 'Edit task' : 'Create task'}</h2></div><button onClick={onClose} className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-2)]"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1 block text-xs text-[var(--muted)]">Title</span><input autoFocus value={form.title} onChange={e => set('title', e.target.value)} className={input}/></label><label className="sm:col-span-2"><span className="mb-1 block text-xs text-[var(--muted)]">Description</span><textarea value={form.description} onChange={e => set('description', e.target.value)} rows={3} className={`${input} resize-none`}/></label><Field label="Priority"><select className={input} value={form.priority} onChange={e => set('priority', e.target.value as TaskFormValues['priority'])}>{['low','medium','high','urgent'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Status"><select className={input} value={form.status} onChange={e => set('status', e.target.value as TaskFormValues['status'])}>{['inbox','planned','in_progress'].map(v => <option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></Field><Field label="Due"><input className={input} type="datetime-local" value={form.due_at} onChange={e => set('due_at', e.target.value)}/></Field><Field label="Start"><input className={input} type="datetime-local" value={form.start_at} onChange={e => set('start_at', e.target.value)}/></Field><Field label="Estimated minutes"><input className={input} type="number" min="1" value={form.estimated_minutes} onChange={e => set('estimated_minutes', e.target.value)}/></Field><Field label="Life area"><select className={input} value={form.life_area_id} onChange={e => set('life_area_id', e.target.value)}><option value="">None</option>{options.lifeAreas.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Goal"><select className={input} value={form.goal_id} onChange={e => set('goal_id', e.target.value)}><option value="">None</option>{options.goals.map(g => <option key={g.id} value={g.id}>{g.title}</option>)}</select></Field></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm">Cancel</button><button disabled={!form.title.trim()} onClick={() => void onSave(form)} className="rounded-xl bg-[var(--accent)] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Save task</button></div></div></div>
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label><span className="mb-1 block text-xs text-[var(--muted)]">{label}</span>{children}</label> }
