import { useCallback, useEffect, useState } from 'react'
import { BookOpen, Edit3, Plus, RefreshCw, Trash2, X } from 'lucide-react'
import { createJournalEntry, deleteJournalEntry, listJournalEntries, updateJournalEntry } from './journalApi'
import type { JournalEntry, JournalInput } from './types'

const today = () => new Date().toISOString().slice(0, 10)
const empty: JournalInput = { entry_date: today(), title: '', content: '', entry_type: 'journal', mood: null }
const inputClass = 'w-full rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-3 py-2.5 outline-none focus:border-[var(--accent)]'

export function JournalPage() {
  const [entries, setEntries] = useState<JournalEntry[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [editor, setEditor] = useState<{ open: boolean; entry: JournalEntry | null }>({ open: false, entry: null })
  const load = useCallback(async () => { setLoading(true); setError(null); try { setEntries(await listJournalEntries()) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load journal.') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  async function save(input: JournalInput) { if (!input.content.trim()) return; try { const saved = editor.entry ? await updateJournalEntry(editor.entry.id, input) : await createJournalEntry(input); setEntries(current => editor.entry ? current.map(item => item.id === saved.id ? saved : item) : [saved, ...current]); setEditor({ open: false, entry: null }) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save entry.') } }
  async function remove(entry: JournalEntry) { if (!window.confirm('Delete this journal entry?')) return; try { await deleteJournalEntry(entry.id); setEntries(current => current.filter(item => item.id !== entry.id)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete entry.') } }
  return <section className="mx-auto max-w-5xl px-5 py-8 lg:px-10">
    <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-[var(--accent)]">Reflection</p><h1 className="text-3xl font-semibold tracking-tight">Journal</h1><p className="mt-2 max-w-2xl text-sm text-[var(--muted)]">Capture what happened, what you learned, and what should change next.</p></div><div className="flex gap-2"><button onClick={() => setEditor({ open: true, entry: null })} className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>New entry</button><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-2.5 text-sm"><RefreshCw size={15}/>Refresh</button></div></header>
    {error && <div className="mb-5 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-sm text-red-200">{error}</div>}
    {loading && !entries.length ? <div className="space-y-3">{[1,2,3].map(i => <div key={i} className="h-32 animate-pulse rounded-2xl bg-[var(--surface)]" />)}</div> : entries.length ? <div className="space-y-3">{entries.map(entry => <article key={entry.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase tracking-wide text-[var(--accent)]">{entry.entry_type}</span><span className="text-xs text-[var(--muted)]">{entry.entry_date}</span>{entry.mood != null && <span className="text-xs text-[var(--muted)]">Mood {entry.mood}/5</span>}</div><h2 className="mt-2 text-lg font-semibold">{entry.title || 'Untitled reflection'}</h2></div><div className="flex shrink-0 gap-1"><button onClick={() => setEditor({ open: true, entry })} className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-2)]"><Edit3 size={15}/></button><button onClick={() => void remove(entry)} className="rounded-lg p-2 text-[var(--muted)] hover:bg-red-500/10 hover:text-red-300"><Trash2 size={15}/></button></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[var(--muted)]">{entry.content}</p>{entry.ai_summary && <p className="mt-4 rounded-xl bg-[var(--surface-2)] p-3 text-xs leading-5 text-[var(--muted)]">AI summary: {entry.ai_summary}</p>}</article>)}</div> : <div className="rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)] p-12 text-center"><BookOpen className="mx-auto text-[var(--accent)]" size={28}/><h2 className="mt-3 font-semibold">Start your reflection loop</h2><p className="mt-1 text-sm text-[var(--muted)]">Write your first journal entry and build a record LifeOS can learn from.</p><button onClick={() => setEditor({ open: true, entry: null })} className="mt-5 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white">Write first entry</button></div>}
    {editor.open && <JournalEditor entry={editor.entry} onClose={() => setEditor({ open: false, entry: null })} onSave={save} />}
  </section>
}

function JournalEditor({ entry, onClose, onSave }: { entry: JournalEntry | null; onClose: () => void; onSave: (input: JournalInput) => Promise<void> }) { const [form, setForm] = useState<JournalInput>(() => entry ? { entry_date: entry.entry_date, title: entry.title ?? '', content: entry.content, entry_type: entry.entry_type, mood: entry.mood } : empty); const set = <K extends keyof JournalInput>(key: K, value: JournalInput[K]) => setForm(v => ({ ...v, [key]: value })); return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/60 p-4"><div className="my-8 w-full max-w-2xl rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--accent)]">Reflection</p><h2 className="mt-1 text-xl font-semibold">{entry ? 'Edit entry' : 'New entry'}</h2></div><button onClick={onClose} className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-2)]"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs text-[var(--muted)]">Date</span><input type="date" className={inputClass} value={form.entry_date} onChange={e => set('entry_date', e.target.value)} /></label><label><span className="mb-1 block text-xs text-[var(--muted)]">Type</span><select className={inputClass} value={form.entry_type} onChange={e => set('entry_type', e.target.value)}><option value="journal">Journal</option><option value="reflection">Reflection</option><option value="gratitude">Gratitude</option><option value="review">Review</option></select></label><label className="sm:col-span-2"><span className="mb-1 block text-xs text-[var(--muted)]">Title</span><input className={inputClass} value={form.title} onChange={e => set('title', e.target.value)} placeholder="What is on your mind?" /></label><label className="sm:col-span-2"><span className="mb-1 block text-xs text-[var(--muted)]">Reflection</span><textarea autoFocus className={`${inputClass} min-h-48 resize-y`} value={form.content} onChange={e => set('content', e.target.value)} placeholder="What happened? What did you learn? What should you do differently?" /></label><label><span className="mb-1 block text-xs text-[var(--muted)]">Mood (1–5)</span><input type="number" min="1" max="5" className={inputClass} value={form.mood ?? ''} onChange={e => set('mood', e.target.value === '' ? null : Math.max(1, Math.min(5, Number(e.target.value))))} /></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm">Cancel</button><button disabled={!form.content.trim()} onClick={() => void onSave(form)} className="rounded-xl bg-[var(--accent)] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Save entry</button></div></div></div> }
